blog/urls.py
from django.urls import path
from .views import render_posts, post_detail

app_name = "blog"

urlpatterns = [
    path("", render_posts, name="posts"),
    path("/<int:post_id>", post_detail, name="post_detail"),           
               ]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views




urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('blog', include('blog.urls'))
]

 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
import datetime


class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to="blog/images")
    url = URLField(blank=True)

portfolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField


class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=250)
    image = ImageField(upload_to="portfolio/images")
    url = URLField(blank=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

def render_posts(request):
    posts = Post.objects.all()
    return render(request, 'posts.html', {'posts': posts})

def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'post_detail.html', {"post": post})

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects= Project.objects.all()
    return render(request, 'home.html', {'projects':projects})

blog/templates/post_detail.html
{% extends 'layout.html' %}

{% block content %}

<div class="text-center">
    <h2>{{post.title}}</h2>
    <h3 class="my-2 h5 text-muted">{{post.date|date:"F jS Y"}}</h3>
    <img src="{{post.image.url}}" alt="{{post.title}}"" class=" img-fluid">
    <h3></h3>
    <div class="my-4">
        <p>{{post.description|safe}}</p>
    </div>

</div>

{% endblock %}

blog/templates/posts.html
{% extends 'layout.html' %}

{% block content %}

{% load static %}

<h1>Posts</h1>

{% for post in posts %}

<div class="p-2">
    <div class="card card-body bg-black">
        <div class="row">
            <div class="col-md-2">
                <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">
            </div>
            <div class="col-5">
                <h2>{{post.title}}</h2>
                <p>{{post.description|striptags|truncatechars:100 }}</p>
                <a href="{{post.url}}" class="btn btn-primary">{{post.url}}</a>
            </div>
        </div>
    </div>
</div>


{% endfor %}

{% endblock %}

portfolio/templates/home.html
{% extends 'layout.html' %}

{% block content %}

{% load static %}
<header class="row bg-black d-flex align-items-center">
    <div class="col-md-2 text-center">
        <img src="{% static 'portfolio/icon2.jpg' %}" alt="">
    </div>

    <div class="col-md-10 my-auto text-center">
        <h1><strong>Matias Serra</strong></h1>
        <h3>Hola!</h3>
        <p>Soy Matías, un apasionado estudiante autodidacta de programación con experiencia en Python, Django, FastAPI,
            análisis de datos y desarrollo web (HTML y CSS). Mi enfoque se centra en la creación de soluciones
            tecnológicas innovadoras y la mejora constante de mis habilidades. Me emociona aprender y enfrentar nuevos
            desafíos en el mundo tecnológico</p>
        <a href="{% static 'portfolio/cv.pdf'%}" class="btn btn-primary btn-lg rounded-0 my-3" target="_blank">
            Downnload CV</a>

    </div>


</header>


<div class="row my-2 text-center">
    <h1>Mis Proyectos</h1>

    {% for project in projects %}

    <div class="col-md-3 p-3">
        <div class="card bg-black card-project">
            <img src="{{project.image.url}}" alt="{{project.title}}" class="card-img-top" />
            <div class="card-body">

                <h2 class="text-white">{{project.title}}</h2>
                <p class="text-white">{{project.description}}</p>

                {% if project.url %}
                <a href="{{project.url}}" class="btn btn-light rounded-0 btn-sm" target="_blank">{{project.url}}</a>

                {% endif %}
            </div>
        </div>
    </div>

    <body>
        <div class="container">
            <header class="row bg-black d-flex justify-content-center align-items-center">
                <div class="col-12 text-center">
                    <h1>Contacto</h1>
                </div>
                <section class="col-md-4">
                    <h2>Contáctame por correo electrónico:</h2>
                    <p>
                        <a href="mailto:matiasserra399@gmail.com" class="btn btn-sm btn-primary"
                            target="_blank">matiasserra399@gmail.com</a>
                    </p>
                    <h3>Mi perfil en GitHub:</h3>
                    <p>
                        <a href="https://github.com/Matiasserra399" class="btn btn-sm btn-primary"
                            target="_blank">GitHub/Matiasserra399</a>
                    </p>
    
                    <h3>Mi perfil en LinkedIn:</h3>
                    <p>
                        <a href="https://www.linkedin.com/in/matias-serra-a01b1b28b" class="btn btn-sm btn-primary"
                            target="_blank">LinkedIn/MatiasSerra</a>
                    </p>
                </section>
            </header>
        </div>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    </body>
            
        





    {% endfor %}

    {% endblock %}
</div>

portfolio/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Portfolio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body class="text-light">

    {% include 'partials/navbar.html' %}

    <div class="conteiner p-4">
        {% block content %}
        {% endblock %}
    </div>

</body>
</html>

portfolio/templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-black">
    <div class="container">
        <a class="navbar-brand fw-bold fst-italic" href="/">MS</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:posts' %}">Proyectos</a>
                </li>
                <li class="nav-item d-flex align-items-center">
                    <a class="btn btn-primary btn-sm" href="{% static 'portfolio/cv.pdf' %}" target="_blank">Download
                        CV</a>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>